include(":feature")
apply(from = "account-details/settings-account-details.gradle.kts")
apply(from = "auth/settings-auth.gradle.kts")
apply(from = "create-loan/settings-create-loan.gradle.kts")
apply(from = "history/settings-history.gradle.kts")
apply(from = "profile/settings-profile.gradle.kts")
apply(from = "loan-details/settings-loan-details.gradle.kts")
apply(from = "main/settings-main.gradle.kts")
apply(from = "onboarding/settings-onboarding.gradle.kts")
apply(from = "onboarding/settings-onboarding.gradle.kts")
apply(from = "profile/settings-profile.gradle.kts")
apply(from = "shell-main/settings-shell-main.gradle.kts")
apply(from = "transaction/settings-transaction.gradle.kts")
apply(from = "transaction-details/settings-transaction-details.gradle.kts")
