//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../credit-api-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './Client'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type CreditsAllQueryParameters = {
  clientId?: number | undefined ;
}

export type CreditsGETQueryParameters = {
  id: number ;
}

export type OverdueQueryParameters = {
  clientId?: number | undefined ;
}

export type RatingQueryParameters = {
  clientId?: number | undefined ;
}

export type RepayQueryParameters = {
  id: number ;
}

export function creditsPOSTUrl(): string {
  let url_ = getBaseUrl() + "/credits";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function creditsPOSTMutationKey(): MutationKey {
  return trimArrayEnd([
      'Client',
      'creditsPOST',
    ]);
}

/**
 * Issue a new loan to a client
 * @param body (optional) 
 * @return Loan issued and funds credited to the account
 */
export function useCreditsPOSTMutation<TContext>(options?: Omit<UseMutationOptions<Types.CreditResponse, unknown, Types.IssueCreditRequest, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.CreditResponse, unknown, Types.IssueCreditRequest, TContext> {
  const key = creditsPOSTMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (body: Types.IssueCreditRequest) => Client.creditsPOST(body),
    mutationKey: key,
  });
}
  
export function creditsAllUrl(clientId?: number | undefined): string {
  let url_ = getBaseUrl() + "/credits?";
if (clientId === null)
    throw new Error("The parameter 'clientId' cannot be null.");
else if (clientId !== undefined)
    url_ += "clientId=" + encodeURIComponent("" + clientId) + "&";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let creditsAllDefaultOptions: Omit<UseQueryOptions<Types.CreditResponse[], unknown, Types.CreditResponse[]>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.CreditResponse[], unknown, Types.CreditResponse[]>, 'queryFn'>> = {
};
export function getCreditsAllDefaultOptions() {
  return creditsAllDefaultOptions;
};
export function setCreditsAllDefaultOptions(options: typeof creditsAllDefaultOptions) {
  creditsAllDefaultOptions = options;
}

export function creditsAllQueryKey(clientId?: number | undefined): QueryKey;
export function creditsAllQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { clientId,  } = params[0] as CreditsAllQueryParameters;

    return trimArrayEnd([
        'Client',
        'creditsAll',
        clientId as any,
      ]);
  } else {
    return trimArrayEnd([
        'Client',
        'creditsAll',
        ...params
      ]);
  }
}
export function __creditsAll(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.creditsAll(
      context.queryKey[2] as number | undefined,axiosConfig    );
}

export function useCreditsAllQuery<TSelectData = Types.CreditResponse[], TError = unknown>(dto: CreditsAllQueryParameters, options?: Omit<UseQueryOptions<Types.CreditResponse[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * List credits for a client
 * @param clientId (optional) Client whose credits to return (required for employees)
 * @return List of credits returned
 */
export function useCreditsAllQuery<TSelectData = Types.CreditResponse[], TError = unknown>(clientId?: number | undefined, options?: Omit<UseQueryOptions<Types.CreditResponse[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useCreditsAllQuery<TSelectData = Types.CreditResponse[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.CreditResponse[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let clientId: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ clientId,  } = params[0] as CreditsAllQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [clientId, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.CreditResponse[], TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __creditsAll(context, axiosConfig) : __creditsAll,
    queryKey: creditsAllQueryKey(clientId),
    ...creditsAllDefaultOptions as unknown as Omit<UseQueryOptions<Types.CreditResponse[], TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * List credits for a client
 * @param clientId (optional) Client whose credits to return (required for employees)
 * @return List of credits returned
 */
export function setCreditsAllData(queryClient: QueryClient, updater: (data: Types.CreditResponse[] | undefined) => Types.CreditResponse[], clientId?: number | undefined) {
  queryClient.setQueryData(creditsAllQueryKey(clientId),
    updater
  );
}

/**
 * List credits for a client
 * @param clientId (optional) Client whose credits to return (required for employees)
 * @return List of credits returned
 */
export function setCreditsAllDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.CreditResponse[] | undefined) => Types.CreditResponse[]) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function creditsGETUrl(id: number): string {
  let url_ = getBaseUrl() + "/credits/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let creditsGETDefaultOptions: Omit<UseQueryOptions<Types.CreditDetailResponse, unknown, Types.CreditDetailResponse>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.CreditDetailResponse, unknown, Types.CreditDetailResponse>, 'queryFn'>> = {
};
export function getCreditsGETDefaultOptions() {
  return creditsGETDefaultOptions;
};
export function setCreditsGETDefaultOptions(options: typeof creditsGETDefaultOptions) {
  creditsGETDefaultOptions = options;
}

export function creditsGETQueryKey(id: number): QueryKey;
export function creditsGETQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { id,  } = params[0] as CreditsGETQueryParameters;

    return trimArrayEnd([
        'Client',
        'creditsGET',
        id as any,
      ]);
  } else {
    return trimArrayEnd([
        'Client',
        'creditsGET',
        ...params
      ]);
  }
}
export function __creditsGET(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.creditsGET(
      context.queryKey[2] as number,axiosConfig    );
}

export function useCreditsGETQuery<TSelectData = Types.CreditDetailResponse, TError = unknown>(dto: CreditsGETQueryParameters, options?: Omit<UseQueryOptions<Types.CreditDetailResponse, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * Get full credit details including repayment schedule
 * @param id Credit ID
 * @return Credit details returned
 */
export function useCreditsGETQuery<TSelectData = Types.CreditDetailResponse, TError = unknown>(id: number, options?: Omit<UseQueryOptions<Types.CreditDetailResponse, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useCreditsGETQuery<TSelectData = Types.CreditDetailResponse, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.CreditDetailResponse, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let id: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ id,  } = params[0] as CreditsGETQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [id, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.CreditDetailResponse, TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __creditsGET(context, axiosConfig) : __creditsGET,
    queryKey: creditsGETQueryKey(id),
    ...creditsGETDefaultOptions as unknown as Omit<UseQueryOptions<Types.CreditDetailResponse, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Get full credit details including repayment schedule
 * @param id Credit ID
 * @return Credit details returned
 */
export function setCreditsGETData(queryClient: QueryClient, updater: (data: Types.CreditDetailResponse | undefined) => Types.CreditDetailResponse, id: number) {
  queryClient.setQueryData(creditsGETQueryKey(id),
    updater
  );
}

/**
 * Get full credit details including repayment schedule
 * @param id Credit ID
 * @return Credit details returned
 */
export function setCreditsGETDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.CreditDetailResponse | undefined) => Types.CreditDetailResponse) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function overdueUrl(clientId?: number | undefined): string {
  let url_ = getBaseUrl() + "/credits/overdue?";
if (clientId === null)
    throw new Error("The parameter 'clientId' cannot be null.");
else if (clientId !== undefined)
    url_ += "clientId=" + encodeURIComponent("" + clientId) + "&";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let overdueDefaultOptions: Omit<UseQueryOptions<Types.OverduePaymentResponse[], unknown, Types.OverduePaymentResponse[]>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.OverduePaymentResponse[], unknown, Types.OverduePaymentResponse[]>, 'queryFn'>> = {
};
export function getOverdueDefaultOptions() {
  return overdueDefaultOptions;
};
export function setOverdueDefaultOptions(options: typeof overdueDefaultOptions) {
  overdueDefaultOptions = options;
}

export function overdueQueryKey(clientId?: number | undefined): QueryKey;
export function overdueQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { clientId,  } = params[0] as OverdueQueryParameters;

    return trimArrayEnd([
        'Client',
        'overdue',
        clientId as any,
      ]);
  } else {
    return trimArrayEnd([
        'Client',
        'overdue',
        ...params
      ]);
  }
}
export function __overdue(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.overdue(
      context.queryKey[2] as number | undefined,axiosConfig    );
}

export function useOverdueQuery<TSelectData = Types.OverduePaymentResponse[], TError = unknown>(dto: OverdueQueryParameters, options?: Omit<UseQueryOptions<Types.OverduePaymentResponse[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * List overdue schedule entries for a client (employees and internal calls only)
 * @param clientId (optional) 
 * @return OK
 */
export function useOverdueQuery<TSelectData = Types.OverduePaymentResponse[], TError = unknown>(clientId?: number | undefined, options?: Omit<UseQueryOptions<Types.OverduePaymentResponse[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useOverdueQuery<TSelectData = Types.OverduePaymentResponse[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.OverduePaymentResponse[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let clientId: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ clientId,  } = params[0] as OverdueQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [clientId, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.OverduePaymentResponse[], TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __overdue(context, axiosConfig) : __overdue,
    queryKey: overdueQueryKey(clientId),
    ...overdueDefaultOptions as unknown as Omit<UseQueryOptions<Types.OverduePaymentResponse[], TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * List overdue schedule entries for a client (employees and internal calls only)
 * @param clientId (optional) 
 * @return OK
 */
export function setOverdueData(queryClient: QueryClient, updater: (data: Types.OverduePaymentResponse[] | undefined) => Types.OverduePaymentResponse[], clientId?: number | undefined) {
  queryClient.setQueryData(overdueQueryKey(clientId),
    updater
  );
}

/**
 * List overdue schedule entries for a client (employees and internal calls only)
 * @param clientId (optional) 
 * @return OK
 */
export function setOverdueDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.OverduePaymentResponse[] | undefined) => Types.OverduePaymentResponse[]) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function meAllUrl(): string {
  let url_ = getBaseUrl() + "/credits/overdue/me";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let meAllDefaultOptions: Omit<UseQueryOptions<Types.OverduePaymentResponse[], unknown, Types.OverduePaymentResponse[]>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.OverduePaymentResponse[], unknown, Types.OverduePaymentResponse[]>, 'queryFn'>> = {
};
export function getMeAllDefaultOptions() {
  return meAllDefaultOptions;
};
export function setMeAllDefaultOptions(options: typeof meAllDefaultOptions) {
  meAllDefaultOptions = options;
}

export function meAllQueryKey(): QueryKey;
export function meAllQueryKey(...params: any[]): QueryKey {
  return trimArrayEnd([
      'Client',
      'meAll',
    ]);
}
export function __meAll(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.meAll(
axiosConfig    );
}

/**
 * List overdue schedule entries for the authenticated client
 * @return OK
 */
export function useMeAllQuery<TSelectData = Types.OverduePaymentResponse[], TError = unknown>(options?: Omit<UseQueryOptions<Types.OverduePaymentResponse[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useMeAllQuery<TSelectData = Types.OverduePaymentResponse[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.OverduePaymentResponse[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  

  options = params[0] as any;
  axiosConfig = params[1] as any;

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.OverduePaymentResponse[], TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __meAll(context, axiosConfig) : __meAll,
    queryKey: meAllQueryKey(),
    ...meAllDefaultOptions as unknown as Omit<UseQueryOptions<Types.OverduePaymentResponse[], TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * List overdue schedule entries for the authenticated client
 * @return OK
 */
export function setMeAllData(queryClient: QueryClient, updater: (data: Types.OverduePaymentResponse[] | undefined) => Types.OverduePaymentResponse[], ) {
  queryClient.setQueryData(meAllQueryKey(),
    updater
  );
}

/**
 * List overdue schedule entries for the authenticated client
 * @return OK
 */
export function setMeAllDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.OverduePaymentResponse[] | undefined) => Types.OverduePaymentResponse[]) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function ratingUrl(clientId?: number | undefined): string {
  let url_ = getBaseUrl() + "/credits/rating?";
if (clientId === null)
    throw new Error("The parameter 'clientId' cannot be null.");
else if (clientId !== undefined)
    url_ += "clientId=" + encodeURIComponent("" + clientId) + "&";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let ratingDefaultOptions: Omit<UseQueryOptions<Types.CreditRatingResponse, unknown, Types.CreditRatingResponse>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.CreditRatingResponse, unknown, Types.CreditRatingResponse>, 'queryFn'>> = {
};
export function getRatingDefaultOptions() {
  return ratingDefaultOptions;
};
export function setRatingDefaultOptions(options: typeof ratingDefaultOptions) {
  ratingDefaultOptions = options;
}

export function ratingQueryKey(clientId?: number | undefined): QueryKey;
export function ratingQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { clientId,  } = params[0] as RatingQueryParameters;

    return trimArrayEnd([
        'Client',
        'rating',
        clientId as any,
      ]);
  } else {
    return trimArrayEnd([
        'Client',
        'rating',
        ...params
      ]);
  }
}
export function __rating(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.rating(
      context.queryKey[2] as number | undefined,axiosConfig    );
}

export function useRatingQuery<TSelectData = Types.CreditRatingResponse, TError = unknown>(dto: RatingQueryParameters, options?: Omit<UseQueryOptions<Types.CreditRatingResponse, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * Credit rating for a client (employees and internal calls only)
 * @param clientId (optional) 
 * @return OK
 */
export function useRatingQuery<TSelectData = Types.CreditRatingResponse, TError = unknown>(clientId?: number | undefined, options?: Omit<UseQueryOptions<Types.CreditRatingResponse, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useRatingQuery<TSelectData = Types.CreditRatingResponse, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.CreditRatingResponse, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let clientId: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ clientId,  } = params[0] as RatingQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [clientId, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.CreditRatingResponse, TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __rating(context, axiosConfig) : __rating,
    queryKey: ratingQueryKey(clientId),
    ...ratingDefaultOptions as unknown as Omit<UseQueryOptions<Types.CreditRatingResponse, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Credit rating for a client (employees and internal calls only)
 * @param clientId (optional) 
 * @return OK
 */
export function setRatingData(queryClient: QueryClient, updater: (data: Types.CreditRatingResponse | undefined) => Types.CreditRatingResponse, clientId?: number | undefined) {
  queryClient.setQueryData(ratingQueryKey(clientId),
    updater
  );
}

/**
 * Credit rating for a client (employees and internal calls only)
 * @param clientId (optional) 
 * @return OK
 */
export function setRatingDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.CreditRatingResponse | undefined) => Types.CreditRatingResponse) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function meUrl(): string {
  let url_ = getBaseUrl() + "/credits/rating/me";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let meDefaultOptions: Omit<UseQueryOptions<Types.CreditRatingResponse, unknown, Types.CreditRatingResponse>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.CreditRatingResponse, unknown, Types.CreditRatingResponse>, 'queryFn'>> = {
};
export function getMeDefaultOptions() {
  return meDefaultOptions;
};
export function setMeDefaultOptions(options: typeof meDefaultOptions) {
  meDefaultOptions = options;
}

export function meQueryKey(): QueryKey;
export function meQueryKey(...params: any[]): QueryKey {
  return trimArrayEnd([
      'Client',
      'me',
    ]);
}
export function __me(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.me(
axiosConfig    );
}

/**
 * Credit rating for the authenticated client
 * @return OK
 */
export function useMeQuery<TSelectData = Types.CreditRatingResponse, TError = unknown>(options?: Omit<UseQueryOptions<Types.CreditRatingResponse, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useMeQuery<TSelectData = Types.CreditRatingResponse, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.CreditRatingResponse, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  

  options = params[0] as any;
  axiosConfig = params[1] as any;

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.CreditRatingResponse, TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __me(context, axiosConfig) : __me,
    queryKey: meQueryKey(),
    ...meDefaultOptions as unknown as Omit<UseQueryOptions<Types.CreditRatingResponse, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Credit rating for the authenticated client
 * @return OK
 */
export function setMeData(queryClient: QueryClient, updater: (data: Types.CreditRatingResponse | undefined) => Types.CreditRatingResponse, ) {
  queryClient.setQueryData(meQueryKey(),
    updater
  );
}

/**
 * Credit rating for the authenticated client
 * @return OK
 */
export function setMeDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.CreditRatingResponse | undefined) => Types.CreditRatingResponse) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function repayUrl(id: number): string {
  let url_ = getBaseUrl() + "/credits/{id}/repay";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function repayMutationKey(id: number): MutationKey {
  return trimArrayEnd([
      'Client',
      'repay',
      id as any,
    ]);
}

/**
 * Fully repay a credit early
 * @param id Credit ID to repay
 * @return Credit fully repaid and closed
 */
export function useRepayMutation<TContext>(id: number, options?: Omit<UseMutationOptions<Types.CreditResponse, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.CreditResponse, unknown, void, TContext> {
  const key = repayMutationKey(id);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.repay(id),
    mutationKey: key,
  });
}
  
type Repay__MutationParameters = RepayQueryParameters

/**
 * Fully repay a credit early
 * @param id Credit ID to repay
 * @return Credit fully repaid and closed
 */
export function useRepayMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.CreditResponse, unknown, Repay__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: RepayQueryParameters}): UseMutationResult<Types.CreditResponse, unknown, Repay__MutationParameters, TContext> {
  const key = repayMutationKey(options?.parameters?.id!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: Repay__MutationParameters) => Client.repay(data.id ?? options?.parameters?.id!),
  mutationKey: key,
});
}
  
export function tariffsAllUrl(): string {
  let url_ = getBaseUrl() + "/tariffs";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let tariffsAllDefaultOptions: Omit<UseQueryOptions<Types.TariffResponse[], unknown, Types.TariffResponse[]>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.TariffResponse[], unknown, Types.TariffResponse[]>, 'queryFn'>> = {
};
export function getTariffsAllDefaultOptions() {
  return tariffsAllDefaultOptions;
};
export function setTariffsAllDefaultOptions(options: typeof tariffsAllDefaultOptions) {
  tariffsAllDefaultOptions = options;
}

export function tariffsAllQueryKey(): QueryKey;
export function tariffsAllQueryKey(...params: any[]): QueryKey {
  return trimArrayEnd([
      'Client',
      'tariffsAll',
    ]);
}
export function __tariffsAll(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.tariffsAll(
axiosConfig    );
}

/**
 * Get all available credit tariffs
 * @return List of tariffs returned
 */
export function useTariffsAllQuery<TSelectData = Types.TariffResponse[], TError = unknown>(options?: Omit<UseQueryOptions<Types.TariffResponse[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useTariffsAllQuery<TSelectData = Types.TariffResponse[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.TariffResponse[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  

  options = params[0] as any;
  axiosConfig = params[1] as any;

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.TariffResponse[], TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __tariffsAll(context, axiosConfig) : __tariffsAll,
    queryKey: tariffsAllQueryKey(),
    ...tariffsAllDefaultOptions as unknown as Omit<UseQueryOptions<Types.TariffResponse[], TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Get all available credit tariffs
 * @return List of tariffs returned
 */
export function setTariffsAllData(queryClient: QueryClient, updater: (data: Types.TariffResponse[] | undefined) => Types.TariffResponse[], ) {
  queryClient.setQueryData(tariffsAllQueryKey(),
    updater
  );
}

/**
 * Get all available credit tariffs
 * @return List of tariffs returned
 */
export function setTariffsAllDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.TariffResponse[] | undefined) => Types.TariffResponse[]) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function tariffsUrl(): string {
  let url_ = getBaseUrl() + "/tariffs";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function tariffsMutationKey(): MutationKey {
  return trimArrayEnd([
      'Client',
      'tariffs',
    ]);
}

/**
 * Create a new credit tariff
 * @param body (optional) 
 * @return Tariff created successfully
 */
export function useTariffsMutation<TContext>(options?: Omit<UseMutationOptions<Types.TariffResponse, unknown, Types.CreateTariffRequest, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.TariffResponse, unknown, Types.CreateTariffRequest, TContext> {
  const key = tariffsMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (body: Types.CreateTariffRequest) => Client.tariffs(body),
    mutationKey: key,
  });
}