//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../credit-api-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './Client'
export { Client };
import type { AxiosRequestConfig } from 'axios';

export type CreditsPOSTQueryParameters = {
  x_User_Id?: number | undefined ;
  x_User_Role?: Types.XUserRole | undefined ;
}

export type CreditsAllQueryParameters = {
  clientId?: number | undefined ;
  x_User_Id?: number | undefined ;
  x_User_Role?: Types.XUserRole2 | undefined ;
}

export type CreditsGETQueryParameters = {
  id: number ;
  x_User_Id?: number | undefined ;
  x_User_Role?: Types.XUserRole3 | undefined ;
}

export type RepayQueryParameters = {
  id: number ;
  x_User_Id?: number | undefined ;
  x_User_Role?: Types.XUserRole4 | undefined ;
}

export type TariffsAllQueryParameters = {
  x_User_Id?: number | undefined ;
  x_User_Role?: Types.XUserRole5 | undefined ;
}

export type TariffsQueryParameters = {
  x_User_Id?: number | undefined ;
  x_User_Role?: Types.XUserRole6 | undefined ;
}

export function creditsPOSTUrl(x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole | undefined): string {
  let url_ = getBaseUrl() + "/credits";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function creditsPOSTMutationKey(x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole | undefined): MutationKey {
  return trimArrayEnd([
      'Client',
      'creditsPOST',
      x_User_Id as any,
      x_User_Role as any,
    ]);
}

/**
 * Issue a new loan to a client
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @param body (optional) 
 * @return Loan issued and funds credited to the acount
 */
export function useCreditsPOSTMutation<TContext>(x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole | undefined, options?: Omit<UseMutationOptions<Types.CreditResponse, unknown, Types.IssueCreditRequest, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.CreditResponse, unknown, Types.IssueCreditRequest, TContext> {
  const key = creditsPOSTMutationKey(x_User_Id, x_User_Role);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (body: Types.IssueCreditRequest) => Client.creditsPOST(x_User_Id, x_User_Role, body),
    mutationKey: key,
  });
}
  
type CreditsPOST__MutationParameters = CreditsPOSTQueryParameters & {
  body: Types.IssueCreditRequest;
}

/**
 * Issue a new loan to a client
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @param body (optional) 
 * @return Loan issued and funds credited to the acount
 */
export function useCreditsPOSTMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.CreditResponse, unknown, CreditsPOST__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: CreditsPOSTQueryParameters}): UseMutationResult<Types.CreditResponse, unknown, CreditsPOST__MutationParameters, TContext> {
  const key = creditsPOSTMutationKey(options?.parameters?.x_User_Id!, options?.parameters?.x_User_Role!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: CreditsPOST__MutationParameters) => Client.creditsPOST(data.x_User_Id ?? options?.parameters?.x_User_Id!, data.x_User_Role ?? options?.parameters?.x_User_Role!, data.body),
  mutationKey: key,
});
}
  
export function creditsAllUrl(clientId?: number | undefined, x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole2 | undefined): string {
  let url_ = getBaseUrl() + "/credits?";
if (clientId === null)
    throw new Error("The parameter 'clientId' cannot be null.");
else if (clientId !== undefined)
    url_ += "clientId=" + encodeURIComponent("" + clientId) + "&";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let creditsAllDefaultOptions: Omit<UseQueryOptions<Types.CreditResponse[], unknown, Types.CreditResponse[]>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.CreditResponse[], unknown, Types.CreditResponse[]>, 'queryFn'>> = {
};
export function getCreditsAllDefaultOptions() {
  return creditsAllDefaultOptions;
};
export function setCreditsAllDefaultOptions(options: typeof creditsAllDefaultOptions) {
  creditsAllDefaultOptions = options;
}

export function creditsAllQueryKey(dto: CreditsAllQueryParameters): QueryKey;
export function creditsAllQueryKey(clientId?: number | undefined, x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole2 | undefined): QueryKey;
export function creditsAllQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { clientId, x_User_Id, x_User_Role,  } = params[0] as CreditsAllQueryParameters;

    return trimArrayEnd([
        'Client',
        'creditsAll',
        clientId as any,
        x_User_Id as any,
        x_User_Role as any,
      ]);
  } else {
    return trimArrayEnd([
        'Client',
        'creditsAll',
        ...params
      ]);
  }
}
export function __creditsAll(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.creditsAll(
      context.queryKey[2] as number | undefined,       context.queryKey[3] as number | undefined,       context.queryKey[4] as Types.XUserRole2 | undefined,axiosConfig    );
}

export function useCreditsAllQuery<TSelectData = Types.CreditResponse[], TError = unknown>(dto: CreditsAllQueryParameters, options?: Omit<UseQueryOptions<Types.CreditResponse[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * List credits for a client
 * @param clientId (optional) Client whose credits to return
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @return List of credits returned
 */
export function useCreditsAllQuery<TSelectData = Types.CreditResponse[], TError = unknown>(clientId?: number | undefined, x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole2 | undefined, options?: Omit<UseQueryOptions<Types.CreditResponse[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useCreditsAllQuery<TSelectData = Types.CreditResponse[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.CreditResponse[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let clientId: any = undefined;
  let x_User_Id: any = undefined;
  let x_User_Role: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ clientId, x_User_Id, x_User_Role,  } = params[0] as CreditsAllQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [clientId, x_User_Id, x_User_Role, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.CreditResponse[], TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __creditsAll(context, axiosConfig) : __creditsAll,
    queryKey: creditsAllQueryKey(clientId, x_User_Id, x_User_Role),
    ...creditsAllDefaultOptions as unknown as Omit<UseQueryOptions<Types.CreditResponse[], TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * List credits for a client
 * @param clientId (optional) Client whose credits to return
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @return List of credits returned
 */
export function setCreditsAllData(queryClient: QueryClient, updater: (data: Types.CreditResponse[] | undefined) => Types.CreditResponse[], clientId?: number | undefined, x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole2 | undefined) {
  queryClient.setQueryData(creditsAllQueryKey(clientId, x_User_Id, x_User_Role),
    updater
  );
}

/**
 * List credits for a client
 * @param clientId (optional) Client whose credits to return
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @return List of credits returned
 */
export function setCreditsAllDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.CreditResponse[] | undefined) => Types.CreditResponse[]) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function creditsGETUrl(id: number, x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole3 | undefined): string {
  let url_ = getBaseUrl() + "/credits/{id}";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let creditsGETDefaultOptions: Omit<UseQueryOptions<Types.CreditDetailResponse, unknown, Types.CreditDetailResponse>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.CreditDetailResponse, unknown, Types.CreditDetailResponse>, 'queryFn'>> = {
};
export function getCreditsGETDefaultOptions() {
  return creditsGETDefaultOptions;
};
export function setCreditsGETDefaultOptions(options: typeof creditsGETDefaultOptions) {
  creditsGETDefaultOptions = options;
}

export function creditsGETQueryKey(dto: CreditsGETQueryParameters): QueryKey;
export function creditsGETQueryKey(id: number, x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole3 | undefined): QueryKey;
export function creditsGETQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { id, x_User_Id, x_User_Role,  } = params[0] as CreditsGETQueryParameters;

    return trimArrayEnd([
        'Client',
        'creditsGET',
        id as any,
        x_User_Id as any,
        x_User_Role as any,
      ]);
  } else {
    return trimArrayEnd([
        'Client',
        'creditsGET',
        ...params
      ]);
  }
}
export function __creditsGET(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.creditsGET(
      context.queryKey[2] as number,       context.queryKey[3] as number | undefined,       context.queryKey[4] as Types.XUserRole3 | undefined,axiosConfig    );
}

export function useCreditsGETQuery<TSelectData = Types.CreditDetailResponse, TError = unknown>(dto: CreditsGETQueryParameters, options?: Omit<UseQueryOptions<Types.CreditDetailResponse, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * Get full credit details including repayment schedule
 * @param id Credit ID
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @return Credit details returned
 */
export function useCreditsGETQuery<TSelectData = Types.CreditDetailResponse, TError = unknown>(id: number, x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole3 | undefined, options?: Omit<UseQueryOptions<Types.CreditDetailResponse, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useCreditsGETQuery<TSelectData = Types.CreditDetailResponse, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.CreditDetailResponse, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let id: any = undefined;
  let x_User_Id: any = undefined;
  let x_User_Role: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ id, x_User_Id, x_User_Role,  } = params[0] as CreditsGETQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [id, x_User_Id, x_User_Role, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.CreditDetailResponse, TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __creditsGET(context, axiosConfig) : __creditsGET,
    queryKey: creditsGETQueryKey(id, x_User_Id, x_User_Role),
    ...creditsGETDefaultOptions as unknown as Omit<UseQueryOptions<Types.CreditDetailResponse, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Get full credit details including repayment schedule
 * @param id Credit ID
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @return Credit details returned
 */
export function setCreditsGETData(queryClient: QueryClient, updater: (data: Types.CreditDetailResponse | undefined) => Types.CreditDetailResponse, id: number, x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole3 | undefined) {
  queryClient.setQueryData(creditsGETQueryKey(id, x_User_Id, x_User_Role),
    updater
  );
}

/**
 * Get full credit details including repayment schedule
 * @param id Credit ID
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @return Credit details returned
 */
export function setCreditsGETDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.CreditDetailResponse | undefined) => Types.CreditDetailResponse) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function repayUrl(id: number, x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole4 | undefined): string {
  let url_ = getBaseUrl() + "/credits/{id}/repay";
if (id === undefined || id === null)
  throw new Error("The parameter 'id' must be defined.");
url_ = url_.replace("{id}", encodeURIComponent("" + id));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function repayMutationKey(id: number, x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole4 | undefined): MutationKey {
  return trimArrayEnd([
      'Client',
      'repay',
      id as any,
      x_User_Id as any,
      x_User_Role as any,
    ]);
}

/**
 * Fully repay a credit early
 * @param id Credit ID to repay
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @return Credit fully repaid and closed
 */
export function useRepayMutation<TContext>(id: number, x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole4 | undefined, options?: Omit<UseMutationOptions<Types.CreditResponse, unknown, void, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.CreditResponse, unknown, void, TContext> {
  const key = repayMutationKey(id, x_User_Id, x_User_Role);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: () => Client.repay(id, x_User_Id, x_User_Role),
    mutationKey: key,
  });
}
  
type Repay__MutationParameters = RepayQueryParameters

/**
 * Fully repay a credit early
 * @param id Credit ID to repay
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @return Credit fully repaid and closed
 */
export function useRepayMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.CreditResponse, unknown, Repay__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: RepayQueryParameters}): UseMutationResult<Types.CreditResponse, unknown, Repay__MutationParameters, TContext> {
  const key = repayMutationKey(options?.parameters?.id!, options?.parameters?.x_User_Id!, options?.parameters?.x_User_Role!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: Repay__MutationParameters) => Client.repay(data.id ?? options?.parameters?.id!, data.x_User_Id ?? options?.parameters?.x_User_Id!, data.x_User_Role ?? options?.parameters?.x_User_Role!),
  mutationKey: key,
});
}
  
export function tariffsAllUrl(x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole5 | undefined): string {
  let url_ = getBaseUrl() + "/tariffs";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let tariffsAllDefaultOptions: Omit<UseQueryOptions<Types.TariffResponse[], unknown, Types.TariffResponse[]>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.TariffResponse[], unknown, Types.TariffResponse[]>, 'queryFn'>> = {
};
export function getTariffsAllDefaultOptions() {
  return tariffsAllDefaultOptions;
};
export function setTariffsAllDefaultOptions(options: typeof tariffsAllDefaultOptions) {
  tariffsAllDefaultOptions = options;
}

export function tariffsAllQueryKey(dto: TariffsAllQueryParameters): QueryKey;
export function tariffsAllQueryKey(x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole5 | undefined): QueryKey;
export function tariffsAllQueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { x_User_Id, x_User_Role,  } = params[0] as TariffsAllQueryParameters;

    return trimArrayEnd([
        'Client',
        'tariffsAll',
        x_User_Id as any,
        x_User_Role as any,
      ]);
  } else {
    return trimArrayEnd([
        'Client',
        'tariffsAll',
        ...params
      ]);
  }
}
export function __tariffsAll(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.tariffsAll(
      context.queryKey[2] as number | undefined,       context.queryKey[3] as Types.XUserRole5 | undefined,axiosConfig    );
}

export function useTariffsAllQuery<TSelectData = Types.TariffResponse[], TError = unknown>(dto: TariffsAllQueryParameters, options?: Omit<UseQueryOptions<Types.TariffResponse[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * Get all available credit tariffs
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @return List of tariffs returned
 */
export function useTariffsAllQuery<TSelectData = Types.TariffResponse[], TError = unknown>(x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole5 | undefined, options?: Omit<UseQueryOptions<Types.TariffResponse[], TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useTariffsAllQuery<TSelectData = Types.TariffResponse[], TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.TariffResponse[], TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let x_User_Id: any = undefined;
  let x_User_Role: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ x_User_Id, x_User_Role,  } = params[0] as TariffsAllQueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [x_User_Id, x_User_Role, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.TariffResponse[], TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __tariffsAll(context, axiosConfig) : __tariffsAll,
    queryKey: tariffsAllQueryKey(x_User_Id, x_User_Role),
    ...tariffsAllDefaultOptions as unknown as Omit<UseQueryOptions<Types.TariffResponse[], TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * Get all available credit tariffs
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @return List of tariffs returned
 */
export function setTariffsAllData(queryClient: QueryClient, updater: (data: Types.TariffResponse[] | undefined) => Types.TariffResponse[], x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole5 | undefined) {
  queryClient.setQueryData(tariffsAllQueryKey(x_User_Id, x_User_Role),
    updater
  );
}

/**
 * Get all available credit tariffs
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @return List of tariffs returned
 */
export function setTariffsAllDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.TariffResponse[] | undefined) => Types.TariffResponse[]) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function tariffsUrl(x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole6 | undefined): string {
  let url_ = getBaseUrl() + "/tariffs";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function tariffsMutationKey(x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole6 | undefined): MutationKey {
  return trimArrayEnd([
      'Client',
      'tariffs',
      x_User_Id as any,
      x_User_Role as any,
    ]);
}

/**
 * Create a new credit tariff
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @param body (optional) 
 * @return Tariff created successfully
 */
export function useTariffsMutation<TContext>(x_User_Id?: number | undefined, x_User_Role?: Types.XUserRole6 | undefined, options?: Omit<UseMutationOptions<Types.TariffResponse, unknown, Types.CreateTariffRequest, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.TariffResponse, unknown, Types.CreateTariffRequest, TContext> {
  const key = tariffsMutationKey(x_User_Id, x_User_Role);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (body: Types.CreateTariffRequest) => Client.tariffs(x_User_Id, x_User_Role, body),
    mutationKey: key,
  });
}
  
type Tariffs__MutationParameters = TariffsQueryParameters & {
  body: Types.CreateTariffRequest;
}

/**
 * Create a new credit tariff
 * @param x_User_Id (optional) Injected by API Gateway — authenticated user ID
 * @param x_User_Role (optional) Injected by API Gateway — authenticated user role
 * @param body (optional) 
 * @return Tariff created successfully
 */
export function useTariffsMutationWithParameters<TContext>(options?: Omit<UseMutationOptions<Types.TariffResponse, unknown, Tariffs__MutationParameters, TContext>, 'mutationKey' | 'mutationFn'> & { parameters?: TariffsQueryParameters}): UseMutationResult<Types.TariffResponse, unknown, Tariffs__MutationParameters, TContext> {
  const key = tariffsMutationKey(options?.parameters?.x_User_Id!, options?.parameters?.x_User_Role!);
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
return useMutation({
  ...options, 
  mutationFn: (data: Tariffs__MutationParameters) => Client.tariffs(data.x_User_Id ?? options?.parameters?.x_User_Id!, data.x_User_Role ?? options?.parameters?.x_User_Role!, data.body),
  mutationKey: key,
});
}