//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../user-api-client.types';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../user-api-client.types';
import { getAxios, getBaseUrl } from './helpers';

/**
 * Issue a JWT token for valid credentials
 * @param body (optional) 
 * @return Token issued successfully
 */
export function login(body?: Types.LoginRequest | undefined, config?: AxiosRequestConfig | undefined): Promise<Types.LoginResponse> {
    let url_ = getBaseUrl() + "/auth/login";
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeLoginRequest(body);

    let options_: AxiosRequestConfig = {
        ..._requestConfigLogin,
        ...config,
        data: content_,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigLogin?.headers,
            "Content-Type": "application/json",
            "Accept": "application/json",
            ...config?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processLogin(_response);
    });
}

function processLogin(response: AxiosResponse): Promise<Types.LoginResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initLoginResponse(resultData200);
        return Promise.resolve<Types.LoginResponse>(result200);

    } else if (status === 401) {
        const _responseText = response.data;
        let result401: any = null;
        let resultData401  = _responseText;
        result401 = Types.initProblemDetails(resultData401);
        return throwException("Invalid credentials or user is blocked", status, _responseText, _headers, result401);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.LoginResponse>(null as any);
}

/**
 * Get the RSA public key used to validate issued JWTs
 * @return Public key returned
 */
export function publicKey(config?: AxiosRequestConfig | undefined): Promise<Types.PublicKeyResponse> {
    let url_ = getBaseUrl() + "/auth/public-key";
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigPublicKey,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigPublicKey?.headers,
            "Accept": "application/json",
            ...config?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processPublicKey(_response);
    });
}

function processPublicKey(response: AxiosResponse): Promise<Types.PublicKeyResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initPublicKeyResponse(resultData200);
        return Promise.resolve<Types.PublicKeyResponse>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.PublicKeyResponse>(null as any);
}

/**
 * Get a list of all users (clients and employees)
 * @return List of users returned
 */
export function usersAll(config?: AxiosRequestConfig | undefined): Promise<Types.UserResponse[]> {
    let url_ = getBaseUrl() + "/users";
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigUsersAll,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigUsersAll?.headers,
            "Accept": "application/json",
            ...config?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processUsersAll(_response);
    });
}

function processUsersAll(response: AxiosResponse): Promise<Types.UserResponse[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        if (Array.isArray(resultData200)) {
              result200 = resultData200.map(item => 
                Types.initUserResponse(item)
              );
            }
        return Promise.resolve<Types.UserResponse[]>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.UserResponse[]>(null as any);
}

/**
 * Create a new client or employee
 * @param body (optional) 
 * @return User created successfully
 */
export function usersPOST(body?: Types.CreateUserRequest | undefined, config?: AxiosRequestConfig | undefined): Promise<Types.UserResponse> {
    let url_ = getBaseUrl() + "/users";
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeCreateUserRequest(body);

    let options_: AxiosRequestConfig = {
        ..._requestConfigUsersPOST,
        ...config,
        data: content_,
        method: "POST",
        url: url_,
        headers: {
            ..._requestConfigUsersPOST?.headers,
            "Content-Type": "application/json",
            "Accept": "application/json",
            ...config?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processUsersPOST(_response);
    });
}

function processUsersPOST(response: AxiosResponse): Promise<Types.UserResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 201) {
        const _responseText = response.data;
        let result201: any = null;
        let resultData201  = _responseText;
        result201 = Types.initUserResponse(resultData201);
        return Promise.resolve<Types.UserResponse>(result201);

    } else if (status === 409) {
        const _responseText = response.data;
        let result409: any = null;
        let resultData409  = _responseText;
        result409 = Types.initProblemDetails(resultData409);
        return throwException("Username is already taken", status, _responseText, _headers, result409);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.UserResponse>(null as any);
}

/**
 * Get a user profile by ID
 * @param id User ID
 * @return User profile returned
 */
export function usersGET(id: number, config?: AxiosRequestConfig | undefined): Promise<Types.UserResponse> {
    let url_ = getBaseUrl() + "/users/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigUsersGET,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigUsersGET?.headers,
            "Accept": "application/json",
            ...config?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processUsersGET(_response);
    });
}

function processUsersGET(response: AxiosResponse): Promise<Types.UserResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initUserResponse(resultData200);
        return Promise.resolve<Types.UserResponse>(result200);

    } else if (status === 404) {
        const _responseText = response.data;
        let result404: any = null;
        let resultData404  = _responseText;
        result404 = Types.initProblemDetails(resultData404);
        return throwException("User not found", status, _responseText, _headers, result404);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.UserResponse>(null as any);
}

/**
 * Block a user
 * @param id User ID
 * @return User blocked successfully
 */
export function block(id: number, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/users/{id}/block";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigBlock,
        ...config,
        method: "PATCH",
        url: url_,
        headers: {
            ..._requestConfigBlock?.headers,
            ...config?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processBlock(_response);
    });
}

function processBlock(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 204) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status === 404) {
        const _responseText = response.data;
        let result404: any = null;
        let resultData404  = _responseText;
        result404 = Types.initProblemDetails(resultData404);
        return throwException("User not found", status, _responseText, _headers, result404);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}

/**
 * Unblock a user
 * @param id User ID
 * @return User unblocked successfully
 */
export function unblock(id: number, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/users/{id}/unblock";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigUnblock,
        ...config,
        method: "PATCH",
        url: url_,
        headers: {
            ..._requestConfigUnblock?.headers,
            ...config?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processUnblock(_response);
    });
}

function processUnblock(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 204) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status === 404) {
        const _responseText = response.data;
        let result404: any = null;
        let resultData404  = _responseText;
        result404 = Types.initProblemDetails(resultData404);
        return throwException("User not found", status, _responseText, _headers, result404);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}
let _requestConfigLogin: Partial<AxiosRequestConfig> | null;
export function getLoginRequestConfig() {
  return _requestConfigLogin;
}
export function setLoginRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigLogin = value;
}
export function patchLoginRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigLogin = patch(_requestConfigLogin ?? {});
}

let _requestConfigPublicKey: Partial<AxiosRequestConfig> | null;
export function getPublicKeyRequestConfig() {
  return _requestConfigPublicKey;
}
export function setPublicKeyRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigPublicKey = value;
}
export function patchPublicKeyRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigPublicKey = patch(_requestConfigPublicKey ?? {});
}

let _requestConfigUsersAll: Partial<AxiosRequestConfig> | null;
export function getUsersAllRequestConfig() {
  return _requestConfigUsersAll;
}
export function setUsersAllRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigUsersAll = value;
}
export function patchUsersAllRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigUsersAll = patch(_requestConfigUsersAll ?? {});
}

let _requestConfigUsersPOST: Partial<AxiosRequestConfig> | null;
export function getUsersPOSTRequestConfig() {
  return _requestConfigUsersPOST;
}
export function setUsersPOSTRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigUsersPOST = value;
}
export function patchUsersPOSTRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigUsersPOST = patch(_requestConfigUsersPOST ?? {});
}

let _requestConfigUsersGET: Partial<AxiosRequestConfig> | null;
export function getUsersGETRequestConfig() {
  return _requestConfigUsersGET;
}
export function setUsersGETRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigUsersGET = value;
}
export function patchUsersGETRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigUsersGET = patch(_requestConfigUsersGET ?? {});
}

let _requestConfigBlock: Partial<AxiosRequestConfig> | null;
export function getBlockRequestConfig() {
  return _requestConfigBlock;
}
export function setBlockRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigBlock = value;
}
export function patchBlockRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigBlock = patch(_requestConfigBlock ?? {});
}

let _requestConfigUnblock: Partial<AxiosRequestConfig> | null;
export function getUnblockRequestConfig() {
  return _requestConfigUnblock;
}
export function setUnblockRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigUnblock = value;
}
export function patchUnblockRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigUnblock = patch(_requestConfigUnblock ?? {});
}