//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../web-app-settings-api-client.types';
import type { AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

import { throwException, isAxiosError } from '../web-app-settings-api-client.types';
import { getAxios, getBaseUrl } from './helpers';

/**
 * @return OK
 */
export function settingsGET(config?: AxiosRequestConfig | undefined): Promise<Types.UserSettingsDto> {
    let url_ = getBaseUrl() + "/api/settings";
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigSettingsGET,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigSettingsGET?.headers,
            "Accept": "text/plain",
            ...config?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processSettingsGET(_response);
    });
}

function processSettingsGET(response: AxiosResponse): Promise<Types.UserSettingsDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initUserSettingsDto(resultData200);
        return Promise.resolve<Types.UserSettingsDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.UserSettingsDto>(null as any);
}

/**
 * @return OK
 */
export function settingsPUT(body: Types.UserSettingsDto, config?: AxiosRequestConfig | undefined): Promise<Types.UserSettingsDto> {
    let url_ = getBaseUrl() + "/api/settings";
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeUserSettingsDto(body);

    let options_: AxiosRequestConfig = {
        ..._requestConfigSettingsPUT,
        ...config,
        data: content_,
        method: "PUT",
        url: url_,
        headers: {
            ..._requestConfigSettingsPUT?.headers,
            "Content-Type": "application/json",
            "Accept": "text/plain",
            ...config?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processSettingsPUT(_response);
    });
}

function processSettingsPUT(response: AxiosResponse): Promise<Types.UserSettingsDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initUserSettingsDto(resultData200);
        return Promise.resolve<Types.UserSettingsDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.UserSettingsDto>(null as any);
}

/**
 * @return OK
 */
export function settingsGET2(userId: number, config?: AxiosRequestConfig | undefined): Promise<Types.UserSettingsDto> {
    let url_ = getBaseUrl() + "/api/settings/{userId}";
    if (userId === undefined || userId === null)
      throw new Error("The parameter 'userId' must be defined.");
    url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
      url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
        ..._requestConfigSettingsGET2,
        ...config,
        method: "GET",
        url: url_,
        headers: {
            ..._requestConfigSettingsGET2?.headers,
            "Accept": "text/plain",
            ...config?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processSettingsGET2(_response);
    });
}

function processSettingsGET2(response: AxiosResponse): Promise<Types.UserSettingsDto> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        let result200: any = null;
        let resultData200  = _responseText;
        result200 = Types.initUserSettingsDto(resultData200);
        return Promise.resolve<Types.UserSettingsDto>(result200);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<Types.UserSettingsDto>(null as any);
}

/**
 * @return OK
 */
export function theme(body: Types.UpdateThemeDto, config?: AxiosRequestConfig | undefined): Promise<void> {
    let url_ = getBaseUrl() + "/api/settings/theme";
      url_ = url_.replace(/[?&]$/, "");

    const content_ = Types.serializeUpdateThemeDto(body);

    let options_: AxiosRequestConfig = {
        ..._requestConfigTheme,
        ...config,
        data: content_,
        method: "PATCH",
        url: url_,
        headers: {
            ..._requestConfigTheme?.headers,
            "Content-Type": "application/json",
            ...config?.headers,
        }
    };

    return getAxios().request(options_).catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
            return _error.response;
        } else {
            throw _error;
        }
    }).then((_response: AxiosResponse) => {
        return processTheme(_response);
    });
}

function processTheme(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
        for (let k in response.headers) {
            if (response.headers.hasOwnProperty(k)) {
                _headers[k] = response.headers[k];
            }
        }
    }
    if (status === 200) {
        const _responseText = response.data;
        return Promise.resolve<void>(null as any);

    } else if (status !== 200 && status !== 204) {
        const _responseText = response.data;
        return throwException("An unexpected server error occurred.", status, _responseText, _headers);
    }
    return Promise.resolve<void>(null as any);
}
let _requestConfigSettingsGET: Partial<AxiosRequestConfig> | null;
export function getSettingsGETRequestConfig() {
  return _requestConfigSettingsGET;
}
export function setSettingsGETRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigSettingsGET = value;
}
export function patchSettingsGETRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigSettingsGET = patch(_requestConfigSettingsGET ?? {});
}

let _requestConfigSettingsPUT: Partial<AxiosRequestConfig> | null;
export function getSettingsPUTRequestConfig() {
  return _requestConfigSettingsPUT;
}
export function setSettingsPUTRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigSettingsPUT = value;
}
export function patchSettingsPUTRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigSettingsPUT = patch(_requestConfigSettingsPUT ?? {});
}

let _requestConfigSettingsGET2: Partial<AxiosRequestConfig> | null;
export function getSettingsGET2RequestConfig() {
  return _requestConfigSettingsGET2;
}
export function setSettingsGET2RequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigSettingsGET2 = value;
}
export function patchSettingsGET2RequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigSettingsGET2 = patch(_requestConfigSettingsGET2 ?? {});
}

let _requestConfigTheme: Partial<AxiosRequestConfig> | null;
export function getThemeRequestConfig() {
  return _requestConfigTheme;
}
export function setThemeRequestConfig(value: Partial<AxiosRequestConfig>) {
  _requestConfigTheme = value;
}
export function patchThemeRequestConfig(patch: (value: Partial<AxiosRequestConfig>) => Partial<AxiosRequestConfig>) {
  _requestConfigTheme = patch(_requestConfigTheme ?? {});
}