//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming
import * as Types from '../web-app-settings-api-client.types';
import { useQuery, useMutation } from '@tanstack/react-query';
import type { UseQueryResult, QueryFunctionContext, UseQueryOptions, QueryClient, QueryKey, MutationKey, UseMutationOptions, UseMutationResult, QueryMeta, MutationMeta } from '@tanstack/react-query';
import { trimArrayEnd, isParameterObject, getBaseUrl, addMetaToOptions } from './helpers';
import type { QueryMetaContextValue } from 'react-query-swagger';
import { QueryMetaContext } from 'react-query-swagger';
import { useContext } from 'react';
import * as Client from './Client'
export { Client };
import type { AxiosRequestConfig } from 'axios';


export type SettingsGET2QueryParameters = {
  userId: number ;
}

export function settingsGETUrl(): string {
  let url_ = getBaseUrl() + "/api/settings";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let settingsGETDefaultOptions: Omit<UseQueryOptions<Types.UserSettingsDto, unknown, Types.UserSettingsDto>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.UserSettingsDto, unknown, Types.UserSettingsDto>, 'queryFn'>> = {
};
export function getSettingsGETDefaultOptions() {
  return settingsGETDefaultOptions;
};
export function setSettingsGETDefaultOptions(options: typeof settingsGETDefaultOptions) {
  settingsGETDefaultOptions = options;
}

export function settingsGETQueryKey(): QueryKey;
export function settingsGETQueryKey(...params: any[]): QueryKey {
  return trimArrayEnd([
      'Client',
      'settingsGET',
    ]);
}
export function __settingsGET(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.settingsGET(
axiosConfig    );
}

/**
 * @return OK
 */
export function useSettingsGETQuery<TSelectData = Types.UserSettingsDto, TError = unknown>(options?: Omit<UseQueryOptions<Types.UserSettingsDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useSettingsGETQuery<TSelectData = Types.UserSettingsDto, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.UserSettingsDto, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  

  options = params[0] as any;
  axiosConfig = params[1] as any;

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.UserSettingsDto, TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __settingsGET(context, axiosConfig) : __settingsGET,
    queryKey: settingsGETQueryKey(),
    ...settingsGETDefaultOptions as unknown as Omit<UseQueryOptions<Types.UserSettingsDto, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * @return OK
 */
export function setSettingsGETData(queryClient: QueryClient, updater: (data: Types.UserSettingsDto | undefined) => Types.UserSettingsDto, ) {
  queryClient.setQueryData(settingsGETQueryKey(),
    updater
  );
}

/**
 * @return OK
 */
export function setSettingsGETDataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.UserSettingsDto | undefined) => Types.UserSettingsDto) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function settingsPUTUrl(): string {
  let url_ = getBaseUrl() + "/api/settings";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function settingsPUTMutationKey(): MutationKey {
  return trimArrayEnd([
      'Client',
      'settingsPUT',
    ]);
}

/**
 * @return OK
 */
export function useSettingsPUTMutation<TContext>(options?: Omit<UseMutationOptions<Types.UserSettingsDto, unknown, Types.UserSettingsDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<Types.UserSettingsDto, unknown, Types.UserSettingsDto, TContext> {
  const key = settingsPUTMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (body: Types.UserSettingsDto) => Client.settingsPUT(body),
    mutationKey: key,
  });
}
  
export function settingsGET2Url(userId: number): string {
  let url_ = getBaseUrl() + "/api/settings/{userId}";
if (userId === undefined || userId === null)
  throw new Error("The parameter 'userId' must be defined.");
url_ = url_.replace("{userId}", encodeURIComponent("" + userId));
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

let settingsGET2DefaultOptions: Omit<UseQueryOptions<Types.UserSettingsDto, unknown, Types.UserSettingsDto>, 'queryKey' | 'queryFn'> & Partial<Pick<UseQueryOptions<Types.UserSettingsDto, unknown, Types.UserSettingsDto>, 'queryFn'>> = {
};
export function getSettingsGET2DefaultOptions() {
  return settingsGET2DefaultOptions;
};
export function setSettingsGET2DefaultOptions(options: typeof settingsGET2DefaultOptions) {
  settingsGET2DefaultOptions = options;
}

export function settingsGET2QueryKey(userId: number): QueryKey;
export function settingsGET2QueryKey(...params: any[]): QueryKey {
  if (params.length === 1 && isParameterObject(params[0])) {
    const { userId,  } = params[0] as SettingsGET2QueryParameters;

    return trimArrayEnd([
        'Client',
        'settingsGET2',
        userId as any,
      ]);
  } else {
    return trimArrayEnd([
        'Client',
        'settingsGET2',
        ...params
      ]);
  }
}
export function __settingsGET2(context: QueryFunctionContext, axiosConfig?: AxiosRequestConfig | undefined) {
  return Client.settingsGET2(
      context.queryKey[2] as number,axiosConfig    );
}

export function useSettingsGET2Query<TSelectData = Types.UserSettingsDto, TError = unknown>(dto: SettingsGET2QueryParameters, options?: Omit<UseQueryOptions<Types.UserSettingsDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
/**
 * @return OK
 */
export function useSettingsGET2Query<TSelectData = Types.UserSettingsDto, TError = unknown>(userId: number, options?: Omit<UseQueryOptions<Types.UserSettingsDto, TError, TSelectData>, 'queryKey'>, axiosConfig?: Partial<AxiosRequestConfig>): UseQueryResult<TSelectData, TError>;
export function useSettingsGET2Query<TSelectData = Types.UserSettingsDto, TError = unknown>(...params: any []): UseQueryResult<TSelectData, TError> {
  let options: UseQueryOptions<Types.UserSettingsDto, TError, TSelectData> | undefined = undefined;
  let axiosConfig: AxiosRequestConfig |undefined = undefined;
  let userId: any = undefined;
  
  if (params.length > 0) {
    if (isParameterObject(params[0])) {
      ({ userId,  } = params[0] as SettingsGET2QueryParameters);
      options = params[1];
      axiosConfig = params[2];
    } else {
      [userId, options, axiosConfig] = params;
    }
  }

  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);

  return useQuery<Types.UserSettingsDto, TError, TSelectData>({
    queryFn: axiosConfig ? (context) => __settingsGET2(context, axiosConfig) : __settingsGET2,
    queryKey: settingsGET2QueryKey(userId),
    ...settingsGET2DefaultOptions as unknown as Omit<UseQueryOptions<Types.UserSettingsDto, TError, TSelectData>, 'queryKey'>,
    ...options,
  });
}
/**
 * @return OK
 */
export function setSettingsGET2Data(queryClient: QueryClient, updater: (data: Types.UserSettingsDto | undefined) => Types.UserSettingsDto, userId: number) {
  queryClient.setQueryData(settingsGET2QueryKey(userId),
    updater
  );
}

/**
 * @return OK
 */
export function setSettingsGET2DataByQueryId(queryClient: QueryClient, queryKey: QueryKey, updater: (data: Types.UserSettingsDto | undefined) => Types.UserSettingsDto) {
  queryClient.setQueryData(queryKey, updater);
}
    
export function themeUrl(): string {
  let url_ = getBaseUrl() + "/api/settings/theme";
  url_ = url_.replace(/[?&]$/, "");
  return url_;
}

export function themeMutationKey(): MutationKey {
  return trimArrayEnd([
      'Client',
      'theme',
    ]);
}

/**
 * @return OK
 */
export function useThemeMutation<TContext>(options?: Omit<UseMutationOptions<void, unknown, Types.UpdateThemeDto, TContext>, 'mutationKey' | 'mutationFn'>): UseMutationResult<void, unknown, Types.UpdateThemeDto, TContext> {
  const key = themeMutationKey();
  
  const metaContext = useContext(QueryMetaContext);
  options = addMetaToOptions(options, metaContext);
  
  return useMutation({
    ...options,
    mutationFn: (body: Types.UpdateThemeDto) => Client.theme(body),
    mutationKey: key,
  });
}